version: '3'

services:
    api:
        build: .
        container_name: best_pizza_api
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

